// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_基本使用;

#nullable disable

namespace _02_组织结构树.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230810123048_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_02_组织结构树.OrgUnits", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentsId");

                    b.ToTable("T_OrgUnits", (string)null);
                });

            modelBuilder.Entity("_02_组织结构树.OrgUnits", b =>
                {
                    b.HasOne("_02_组织结构树.OrgUnits", "Parents")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentsId");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("_02_组织结构树.OrgUnits", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
